name: nikolado
recipe: laravel
config:
  webroot: public
  php: '8.2'
  via: apache
  database: 'mysql'
  xdebug: false
  cache: redis
services:
  myservice:
    type: php
    build_as_root:
      # Note that you will want to use the script for the major version of node you want to install
      # See: https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions
      - curl -sL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs
tooling:
  node:
    service: myservice
  npm:
    service: myservice
